- config/defaults.json
- config/expected-deep.json
```
config/(defaults, expected-deep).json
-Add a default value for the pelias/api configuration property
introduced in https://github.com/pelias/api/pull/123 .
```
fixes pelias/api#8
> Define a default api.accessLog value.

- config/defaults.json
- config/env.json
- config/expected-deep.json
- config/local.json
following on from https://github.com/pelias/openaddresses/pull/20
- add default paths for `openaddresses` imports
- update ES API version to `1.7`
@pelias/contributors if you explicitly set your `esclient.apiVersion` in `~/pelias.json` and wish to stay up-to-date with the development cycle you should now remove that setting from your local config.
you can confirm if it's set with the following command:
```bash
$ grep apiVersion ~/pelias.json
"apiVersion": "1.3",
```
@heffergm and those running pelias in production may still opt to select the api version manually, it should correspond to the highest [available javascript api version](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/about.html) relative to what you have installed in production.
for clarity, …
> add default paths for openaddresses; update ES API version

- config/defaults.json
remove ny as a default file for openaddresses
> remove ny as a default file for openaddresses

- package.json
Without this, I get 
```
npm WARN EPEERINVALID precommit-hook@1.0.7 requires a peer of jshint@ but none was installed.
```
> Add a peer of jshint, required by precommit-hook.

- config/defaults.json
- config/env.json
- config/expected-deep.json
- config/local.json
We discovered a while back that these are not used anywhere.
> Remove depricated OSM type section

- config/defaults.json
- config/expected-deep.json
This will help make the settings clearer for documentation. In general
it would be great to see the defaults.json file explicitly list all
defaults.
> Explicitly set adminLookup to false as defaults

- config/defaults.json
- config/expected-deep.json
Many many users of Pelias are confused by the lack of output at the
`info` level. Adding debug output by default will help make errors and
even successful output more clear.
> Default to debug logging

- config/defaults.json
- config/expected-deep.json
This PR upgrades the default elasticsearch-js API version from 1.7 to 2.2 in order to get access to all the new APIs in 2+
For the most part this won't affect us as the APIs we use have not changed (AFAIK).
I would recommend that all users update their `~/pelias.json` config (or ENV config) file to remove any mention of `esclient.apiVersion`, so they inherit the default value from the defaults file.
Connects pelias/pelias#325
> upgrade ES API version from 1.7->2.2

- config/defaults.json
- config/expected-deep.json
As part of https://github.com/pelias/api/issues/334, we want to be able to configure the Elasticsearch index name that is used by the API, and separately, the importers.
This is a backwards compatible config that adds configuration defaults
for Elasticsearch index names for both the API and schema (which is also
intended to be used by the importers).
While this change by itself doesn't affect anything, **it is what will determine what the config parameter names are for changing which Elasticsearch index to use**, so if there is anything confusing about the current names, this is the best time to change them.
Connects https://github.com/pelias/api/issues/334
> feat: Add default index names for API and schema

- config/defaults.json
- config/expected-deep.json
Because the venue data is quite large, this defaults to false.
> Add default flag for WOF venue import

- config/defaults.json
- config/expected-deep.json
These were buried in [pelias/schema](https://github.com/pelias/schema/blob/f28002db187f1685abc3688b141e0bfdd5cdd01a/settings.js#L289-L296) and will be removed in another PR.
Note that [both](https://github.com/pelias/config/commit/ac95ac8f7e258d22e2c4ced661d21f5fe2f13fba) [commits](https://github.com/pelias/config/commit/0e3fd2c63f43f1c6f4c982597173ef730668abe5) have nice big friendly commit messages with information about these settings. Because JSON doesn't have any support for comments, hopefully people will look at `git blame` when trying to find information on these settings, so I tried to include as much as possible.
Connects pelias/schema#178
> Add Elasticsearch settings

- config/defaults.json
- config/expected-deep.json
The previous target, 2.x, is going away in newer versions of the Elasticsearch NPM module, which we'd like to use. The default will [track the latest version of ES](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/configuration.html#config-options) so we need to explicitly set it to 2.3.
> fix: Set Elasticsearch API version to 2.3

- config/defaults.json
- config/expected-deep.json
This can be overridden once the Geonames importer supports it.
> feat: Add default country code for Geonames

- config/defaults.json
- config/expected-deep.json
- config/local.json
- test/generate.js
interpolation client config
allows configuration of the interpolation client via a config such as:
```bash
"interpolation": {
"client": {
"adapter": "http",
"host": "http://localhost:9999"
}
},
```
with the default being:
```
"interpolation": {
"client": {
"adapter": "null"
}
},
```
**note:** the 'adapter' value will allow for different access protocols in the future, for now the intended options will be `http` and `require`, any other option will fall back to the `NullAdapter` which simply does a no-op (out of scope for this PR, see the corresponding PR in pelias/api).
> interpolation client config

- .jshintrc
- index.js
- package.json
- test/generate.js
removed `.bind()`, defaults deep to true, both parameters are optional
> added schema parameter to generate for auto-validation

- config/defaults.json
- config/expected-deep.json
With the [recent changes](https://github.com/pelias/wof-admin-lookup/pull/89) to integrate
admin lookup into only the wof-admin-lookup, repository, we've also
added a global, instead of per-importer flag to enable admin lookup.
At the same time, we've finally come to the conclusion that admin lookup
should be enabled by default. Despite telling users to enable it after
they understand the memory consequences in our installation guide,
everyone expects cities and other admin areas in their results even when
they haven't enabled it. This makes sense, since the behavior without
admin lookup isn't as good, and the default experience should be good.
So this PR sets that global admin lookup flag to _true_, meaning all
importers will default to using admin lookup, unless it's disabled.
This …
> feat: Add admin lookup config section defaults

- index.js
- test/generate.js
Previously, the supplied schema to `generate` was just validated against but we weren't taking advantage of Joi's ability to add default values and massage types.  For example, in the WOF importer, the code does this at the top: 
`var peliasConfig = require( 'pelias-config' ).generate(require('./schema'));`
but then the code would have to substitute in default values manually and know all the accepted types.  
This change returns the validated config from `generate` so the defaults are populated.  We won't have to check to see if `importVenues` was set to `yes` and then convert that to `true` since Joi does that for us.
> generated now returns validated config with defaults and types massaged

- config/defaults.json
- config/expected-deep.json
At this point, using addressit for search and structured search is
basically an unsupported configuration, since we haven't tested it in
some time. It may in fact even cause errors like those seen in
https://github.com/pelias/pelias/issues/579.
> Default to enabling libpostal in the api

- config/defaults.json
- config/expected-deep.json
Elasticsearch uses 5 shards by default.
> Changed default elasticsearch num of shards to 5

- config/defaults.json
- config/expected-deep.json
Newer versions of `elasticsearch-js` ship only with support for the highest minor version of old major elasticsearch versions. This means that the newest versions have dropped support for the `2.3` API. `2.4` is the only API version supported nopw.
We currently use 2.3 in production for Mapzen Search, but as mentioned in the changelog[1], using API version 2.4 will work just fine. As defined in the rules of semver, only new API calls could be added in 2.4, so anything that works in 2.3 will still be fine.
Changing this version allows us to upgrade to newer versions of `elasticsearch-js` which support the latest versions of Elasticsearch 5, making it easier to upgrade.
[1] https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/changelog.html#_13_0_0_apr_24_2017 …
> feat: change default Elasticsearch API version to 2.4

- config/defaults.json
- config/expected-deep.json
This PR moves the hard-coded list of sources/layers from the `pelias/api` codebase in to `pelias/config`.
This will allow external developers to add their own sources/layers without having to modify source code.
> feat(targets): add API filter targets to config

- README.md
- index.js
- package.json
- test/generate.js
The [pelias/mergeable](https://github.com/pelias/mergeable) package is not really maintained, and doesn't do anything Lodash can't.
In the interests of reducing the number of packages and amount of code we maintain, this PR replaces Mergeable with Lodash in this package.
**Note:** Before merging this, we should check that none of our other packages use any of the [interface functions](https://github.com/pelias/mergeable#interface) Mergeable provides, as the result of a config is now a plain old Javascript object.
Connects https://github.com/pelias/mergeable/issues/5
> Replace Mergeable with Lodash

- index.js
- test/generate.js
Usage of `path.resolve` was erroneously removed in https://github.com/pelias/config/pull/89.
Without `path.resolve`, relative paths are evaluated as relative to the location of the `pelias-config` module, not the current working directory, as is likely intended.
> fix(PELIAS_CONFIG): properly suport relative paths

- config/defaults.json
- test/expected-deep.json
This is a default value for the change in https://github.com/pelias/logger/pull/47
that allows logs to be configured to be emitted as JSON.
Adding the current default value, which keeps JSON logs disabled to
avoid making any changes, will help make things more clear.
> Set default for JSON logs

- index.js
- test/generate.js
This adds a `.get()` function to all config objects made with `generate()`.
Like [Lodash _.get](https://lodash.com/docs/4.17.4#get) it allows easily fetching nested keys in objects with safe handling of undefined values.
> feat(get): add get helper method

- index.js
- test/generate.js
This adds two new functions to the `pelias-config` module:
Always returns the default config, with the `get` function added. While we currently expose a `defaults` object in the module, this won't have the very useful get function added in https://github.com/pelias/config/pull/101
Returns a config object with custom changes applied. It takes two parameters: `custom_config`, which is an object just like what might be found in a users `pelias.json`, and `deep`, which determines if a deep or shallow merge is performed.
Like, `generate`, deep defaults to true. And like `generateDefault`, a proper `get` function is added to all returned objects.
Both of these functions can be very useful in unit tests. Without them, it's a lot of work to create valid `pelias-config` objects.
> feat(generate): Add custom and default config helper functions

- index.js
- test/generate.js
If a schema was passed for validation, the returned config object did not have the `get` function defined.
This adds a helper method for schema validation which ensures the resulting config object is correct.
> Fix schema validation

- .travis.yml
Travis-CI has or will shortly make in early December 2018 a number of beneficial
changes to their Linux continuous integration testing infrastructure.
Changes that impact `pelias/config` are:
* Linux infrastructure combined into one (virtualized), from two previously
(virtualized and container-based). [0][1]
* Offering a more modern, supported Ubuntu Xenial (16.04 LTS) [2]
Projects using `"sudo: false"` (container-based infrastructure), have been
recommended to remove that configuration soon. In any case, the transition
will happen regardless for projects by December 7, 2018.
[0] https://blog.travis-ci.com/2018-10-04-combining-linux-infrastructures
[1] https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration
[2] https://docs.travis-ci.com/user/reference/xenial/
> travis: reflect new best-practice travis-ci configuration

- config/defaults.json
- test/expected-deep.json
The csv-importer's config validation requires the "csv" section is at least present.
Connects https://github.com/pelias/docker/pull/27
> feat(importers): Add empty "csv" section to config

- config/defaults.json
- test/expected-deep.json
This is the official last step to finish up https://github.com/pelias/pelias/issues/461 and mark Elasticsearch 5 as the default version for Pelias.
It allows us to start work on support for Elasticsearch 6 and upgrade to elasticsearch-js 16.x
Connects https://github.com/pelias/pelias/issues/461
Connects https://github.com/pelias/schema/pull/360
Connects https://github.com/pelias/api/pull/1286
Fixes https://github.com/pelias/pelias/issues/461
> Make Elasticsearch 5.6 the default

- config/defaults.json
- test/expected-deep.json
the static type declaration in [pelias/model](https://github.com/pelias/model/blob/203ce7952c6848ca47bb5b93acc69cc9711a0af3/Document.js#L146-L149) makes it very hard to test forwards compatibility with ES7.
this PR introduces a new variable which can be read from within `pelias/schema` & `pelias/model` to control the name of the `_type` name at runtime.
I'll write up some more on the `pelias/model` ticket but the motivation is being *able to* create indices compatible with ES7 while not yet breaking backwards support for ES5.
I see this as a fairly temporary measure and once we've dropped support for ES5 we can remove this setting again (at that stage `_type` will no longer be a 'thing' in ES anyway).
But for now, it's essential for being able to test code across the breaking change.
> support for dynamically specifying the elasticsearch _type from config

- config/defaults.json
- test/expected-deep.json
this PR updates the config to use the elasticsearch v6 APIs by default
> set elasticsearch6 as default

- config/defaults.json
- test/expected-deep.json
None of these URLs have worked in two years, and there's really no
reason for them to be the default.
Connects https://github.com/pelias/pelias/issues/703
> Remove Mapzen services from default endpoints

- config/defaults.json
- test/expected-deep.json
Now that we have dropped support for ES5, we can change the default type name from `doc` to `_doc`. Either setting is compatible with ES6, but only `_doc` is compatible with ES7.
This change has already been set in all the Docker projects via https://github.com/pelias/docker/pull/148, so this change is already well tested.
Connects https://github.com/pelias/pelias/issues/831
> feat(elasticsearch): Default to `_doc` as type name for ES7 support

- config/defaults.json
- test/expected-deep.json
These take very little additional space, and are quite useful.
We should have enabled this a long time ago.
Closes https://github.com/pelias/config/issues/61
> feat(config): Default `whosonfirst.importPostalcodes` to true

- config/defaults.json
- test/expected-deep.json
default `esclient.apiVersion` to 7.x
> fix(esclient): default esclient.apiVersion to 7.x

- config/defaults.json
- test/expected-deep.json
This is now a deprecated options.
related: pelias/whosonfirst#487
> Remove default value for `imports.whosonfirst.importVenues`

- config/defaults.json
- test/expected-deep.json
For quite a while now we've had a solution to the "Postal Cities problem" (https://github.com/pelias/pelias/issues/396), but it was disabled by default.
Enough time has passed that it should probably be enabled.
Closes https://github.com/pelias/pelias/issues/396
> feat: Enable Postal Cities by default

- index.js
- test/generate.js
I noticed today that we have code such as:
`config.get('imports.whosonfirst.dataHost') || DATA_GEOCODE_EARTH_URL`
I tried to update this to use the `$defaultValue` argument provided by lodash (third arg):
`config.get('imports.whosonfirst.dataHost', DATA_GEOCODE_EARTH_URL)`
... but to my surprise this isn't supported!
this PR uses `bind` to ensure that we are supporting all arguments of the lodash function `_.get()`
https://lodash.com/docs/4.17.15#get
I don't think this alone justifies the cascading `npm` upgrade dance but maybe we can merge this at the same time as we're next doing that anyway 😄
> support for lodash get defaultValue

- config/defaults.json
- test/expected-deep.json
I would like to change the default value of [targets.auto_discover](https://github.com/pelias/api#custom-sources-and-layers) from `false` to `true`.
It seems like in the majority of cases having `auto_discover=true` is preferable, the only case where this setting is not preferable is when running a very large index (like planet-wide) using only canonical sources (like Geocode Earth does).
There is a small startup delay of a couple seconds in those 'enterprise-level' installations of Pelias, and the concern is that the server would announce 'ready' to a load-balancer before it loaded its sources/layers from the DB.
> note: canonical sources/layers are used until the auto_discover request returns, so the server can still respond to traffic
I think this setting would be better off defaulting …
> default targets.auto_discover=true

- config/defaults.json
- test/expected-deep.json
For some time, apparently, there have been two `continent` entries in some of our default layer configuration data. Overall, this hasn't had any significant negative effect, since this list is mostly used in places that eventually de-duplicate it.
Worst case, some Elasticsearch filters and error messages have listed the continent layer twice, which is redundant but not going to break anything.
It's obviously better fixed though, and makes writing some API unit tests a bit simpler :)
> Remove duplicate `continent` entry

- config/defaults.json
- test/expected-deep.json
This PR adds a default OpenAddresses token which can be used to authenticate downloads to `batch.openaddresses.io`.
One of the changes from the legacy `results.openaddresses.io` domain to the new `batch` domain was the introduction of token credentials for downloads. The purpose of this change was to better track and prevent abuse of the download server.
Requiring each new Pelias user to register their own account at https://batch.openaddresses.io would add some unnecessary friction to the new user onboarding experience with Pelias.
After discussing this with the OA team we settled on this idea of having a *default shared credential* which will 'just work' out-of-the-box.
Using this default token comes with some caveats that users should be aware of:
- throttling/bandwidth limits will be …
> oa: add shared community token

- config/defaults.json
- test/expected-deep.json
:wave:
We are using `pelias-csv-importer` to import the huge dataset into `elasticsearch`
We have experienced that the performance is not optimal with the current batch size, given our resources.
---
In the process of improving the performance of import, we have experienced that there is no way to configure the batch size when making the bulk import request to elasticsearch via `pelias-dbclient`.
The `pelias-csv-importer` is using the `pelias-dbclient` which has the batch size of 500 hardcoded in the `Batch.js`.
It would be nice to make it configurable.
---
Added the batchSize configuration option under dbclient configuration, and defaults it to 500 as it is in the `pelias-dbclient` now.
---
I have created the [PR#125](https://github.com/pelias/dbclient/pull/125) on `pelias-dbclient` to …
> Adding the option for configuring the batch size.

- config/defaults.json
- test/expected-deep.json
---
I'd like Pelias to run on elasticsearch 8 some day. This is a step towards that.
[Pelias does not support es6](https://github.com/pelias/documentation/blob/master/requirements.md#elasticsearch). Mapping types were first deprecated in es6 and optional with es7, but are now breaking with my es8 tests. 
---
I removed `typeName` from the default config.
In es6 it was recommended to be "_doc".
In es7 it was optional, but if specified it was required to be "_doc".
In es8 it's not allowed at all.
See more:
https://www.elastic.co/guide/en/elasticsearch/reference/7.17/removal-of-types.html
---
I [ran the existing tests](https://github.com/michaelkirk-pelias/config/actions/runs/5513525025) and have successfully utilized this in the context of https://github.com/pelias/schema/pull/490
> Remove unused `typeName` which was deprecated in es7, forbidden in es8
